### PR TITLE
updates on product section and navbar

### PR DESCRIPTION
**Pull request by Enthusiash**
## Changes

- Change active link color
- Remove 2 products
- Change a text spelling

### CODE REVIEW

**Comment by Enthusiash** [comment]
@warengonzaga , Sir eto po tama ba ginawa namin?

**Comment by warengonzaga** [comment]
Hey @Enthusiash let's talk in english here hehe. You can preview your build from the Vercel bot response to see if your build is correct.

**Comment by warengonzaga** [comment]
Just click the preview from the Vercel.

Here's your preview link: https://web3phl-homepage-git-fork-enthusiash-dev-ossph.vercel.app/

@Enthusiash

**Comment by warengonzaga** [comment]
Also, describe your changes, thanks!

**Comment by warengonzaga** [comment]
Another thing I noticed, can you remove this?

image

We should not announce or release this, we'll add this very soon.

**Comment by Enthusiash** [comment]
We've done the changes sir

- Change active link color
- Remove 2 products
- Change a text spelling

**Comment by warengonzaga** [comment]
All right, the only thing concerns me is when you access the site on mobile. Try it you'll find out.

**Review by warengonzaga — APPROVED** [review]
LGTM, however, if you folks can take a look into the mobile version of the site you see some styling issues specifically with the navbar.

**Comment by warengonzaga** [comment]
@Enthusiash not good in styling

image

**Comment by Enthusiash** [comment]
Okay sir, got it!

**Review by warengonzaga — CHANGES_REQUESTED** [review]
Hey @Enthusiash @JBenedicto13 I checked the Nav. It floats without any background but it's sticky which is good. Kindly add a nice background here. Thankies!

image

**Comment by JBenedicto13** [comment]
@warengonzaga I have made new changes for products on homepage and about the background of navbar. Please check.

**Review by warengonzaga — CHANGES_REQUESTED** [review]
While doing the test, I found this bug when you scroll the content, it has some delay before appearing the background for the Navbar.

image

**Comment by warengonzaga** [comment]
Hey @Enthusiash @JBenedicto13 kindly review the comment from your last commit. Thanks!

**Comment by JBenedicto13** [comment]
@warengonzaga I have adjusted the background animation delay. Please check.
image

**Review by warengonzaga — APPROVED** [review]
LGTM! We can address other things in the next PR.

**Pull request merged**
