### PR TITLE
🚀 release: v4.0.1

### LINKED ISSUE #17: remove contact form replace with email address
Let's replace this with an email address instead `gm@web3philippines.org` thanks!

### PR DESCRIPTION
**Pull request by warengonzaga**
## Changes

- #15

### CODE REVIEW

**Comment by warengonzaga** [comment]
Hey @Enthusiash @JBenedicto13 kindly take a look into the issue #17 thanks!

**Comment by warengonzaga** [comment]
Another thing to add kindly check #18 for another quick win for us with this version update. @JBenedicto13 @Enthusiash

**Comment by warengonzaga** [comment]
Good work on this @JBenedicto13 any other updates you need to add? LGTM for me we can now merge this to the main branch.

**Comment by warengonzaga** [comment]
@JBenedicto13 has a problem, when you visit this preview link: https://staging.web3philippines.org you'll see that the banner images are pointing on the local path. Kindly move the assets to the public folder and use the normal path to access the file.

`https://staging.web3philippines.org/src/assets/images/banner_r.jpg`

We can convert this to `https://staging.web3philippines.org/banner_r.jpg`

**Comment by JBenedicto13** [comment]
@Enthusiash has made a PR #20  for the banner revision and added media query for contact page. Please check @warengonzaga

**Comment by warengonzaga** [comment]
@JBenedicto13 wrong path again.

When you place any files in `public` they will directly be available after the domain name.

So from `https://staging.web3philippines.org/public/banner_r.jpg` it should be like this `https://staging.web3philippines.org/banner_r.jpg`

I would suggest testing your builds and trying to host it before you submit your PR.

cc: @Enthusiash

**Pull request merged**
