### PR TITLE
Update year copyright 👋.

### LINKED ISSUE #5: update year copyright
Happy new year 🎊 🎉 web3ph.

### PR DESCRIPTION
**Pull request by mpotane**
Closes #5

### CODE REVIEW

**Comment by mpotane** [comment]
Oh maintainer only mga paps?

**Comment by warengonzaga** [comment]
> Oh maintainer only mga paps?

Will take a look to your PR.

**Comment by warengonzaga** [comment]
Can you make it dynamic? Use something like this https://updateyourfooter.com/ or use a component.

**Comment by mpotane** [comment]
+1 intelligence, +2 luck pag na merge to. 😁

**Comment by warengonzaga** [comment]
Hey @mpotane closing this as someone already made it.

**Pull request closed without merging**
